name: Auto close bad PR
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  pull_request:
    branches:
      - master
      - '*-maintenance'

permissions:
  pull-requests: write

jobs:
  close-pr:
    runs-on: ubuntu-22.04
    steps:
      - name: autoclose
        shell: bash
        if: ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}} == 'master'
        run: gh pr close --comment "Auto-closing pull request because the branch is named `master`. Please create a feature branch instead. https://betaflight.com/docs/development#using-git-and-github"
